### ISSUE TITLE
Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException

### ISSUE THREAD

**Issue by spottedmahn** [luminous-software/extensibility-logs#8]
### Installed product versions
- Visual Studio: 2019 Preview (16.2.0 Preview 1)
- This extension: 1.4

### Description

![image](https://user-images.githubusercontent.com/14079228/58709793-ead30680-8388-11e9-8a1e-9518cba8ea24.png)

>5/31/2019 9:41:43 AM - Skipping 'C:\Users\mdepouw\AppData\Local\Microsoft SDKs' as it doesn't exist
5/31/2019 9:41:43 AM - Beginning to install extension to Microsoft Visual Studio Enterprise 2019...
5/31/2019 9:41:43 AM - Upgrading 'Extensibility Logs', version 1.4 to version 1.5.0.
5/31/2019 9:41:44 AM - Install Error : Microsoft.VisualStudio.ExtensionManager.MissingReferencesException: This extension cannot be installed because the following references are missing:
-Microsoft.VisualStudio.Component.CoreEditor (Microsoft.VisualStudio.Component.CoreEditor)
   at Microsoft.VisualStudio.ExtensionManager.EngineUtilities.EnsureNoMissingReferences(IEnumerable`1 missingRefs)
   at Microsoft.VisualStudio.ExtensionManager.PackageInstaller.PrepareEngineInstall(IDependencyGraph dGraph, IDependencyComparisonSeed seed, Component vsixComponent, Boolean isProductComponent, Int32& totalInstallationSteps)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

### Steps to recreate
1. Upgrade from 1.4 to 1.5 in VS 2019 Preview

### Current behavior
Install error

### Expected behavior
No exeception 😊

**Comment by yannduran** [comment]
v1.5.1 has been uploaded,which should fix the installation problem. Please let me know if you have any more problems :-)

**Comment by spottedmahn** [comment]
gtg, thanks!
